# Generated by Django 3.2.7 on 2021-09-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('mobile_brand', models.CharField(max_length=255)),
                ('mobile_model', models.CharField(max_length=255)),
                ('mobile_IMEI', models.CharField(max_length=255)),
                ('estimated_amount', models.IntegerField()),
                ('estimated_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
